php_variations:
  - name: cli
    default: true
  #- name: fpm
  #- name: fpm-apache
    supported_os: # Open a discussion on serversideup/php if you want to see Alpine support for fpm-apache (https://github.com/serversideup/docker-php/discussions/66)
      - bullseye
      - bookworm
      - trixie
      - buster
  - name: fpm-nginx
# - name: frankenphp
    excluded_minor_versions:
      - "7.0"
      - "7.4"
      - "8.0"
      - "8.1"
      - "8.2"

php_versions:
  - major: "7"
    minor_versions:
      - minor: "7.0"
        base_os:
          - name: buster
        patch_versions:
          - 7.0.33
      - minor: "7.4"
        base_os:
          - name: bullseye
        patch_versions:
          - 7.4.33
  - major: "8"
    minor_versions:
      - minor: "8.0"
        base_os:
          - name: bullseye
        patch_versions:
          - 8.0.30
      - minor: "8.1"
        base_os:
          - name: bookworm
          - name: trixie
        patch_versions:
          # - 8.1.28 # Pull latest from Official PHP source
      - minor: "8.2"
        base_os:
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.2.18 # Pull latest from Official PHP source
      - minor: "8.3"
        base_os:
          - name: bookworm
          - name: trixie
        patch_versions:
          # - 8.3.6 # Pull latest from Official PHP source
      - minor: "8.4"
        base_os:
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.4.1 # Pull latest from Official PHP source
      - minor: "8.5"
        base_os:
          - name: bookworm
          - name: trixie
        patch_versions:
        #   - 8.5.0 # Pull latest from Official PHP source

operating_systems:
  - family: debian
    default: true
    versions:
      - name: "Debian Buster"
        version: buster
        number: 10
        nginx_version: 1.20.2-1~buster
      - name: "Debian Bullseye"
        version: bullseye
        number: 11
        nginx_version: 1.28.0-1~bullseye
      - name: "Debian Bookworm"
        version: bookworm
        number: 12
        nginx_version: 1.28.0-1~bookworm
      - name: "Debian Trixie"
        version: trixie
        number: 13
        nginx_version: 1.28.0-1~trixie
